### PR TITLE
Added shapekey pruner

### PR DESCRIPTION
**Pull request by ptrcortes**
This PR adds a new feature to the shapekey menu: removing unused shapekeys.

This is my first ever blender code and my first actual code change to this package, so I'm anticipating feedback!

Thank you in advance.

### CODE REVIEW

**Comment by ptrcortes** [comment]
I should add that this code also worked in blender 3.6

**Comment by RinaDev-xyz** [comment]
Hi there, we not really adding many new features to Cats, however I will add this as it could be useful for some. 

We are focusing mainly on our Cats Replacement Avatar Toolkit: https://github.com/teamneoneko/Avatar-Toolkit which where new features will be added in the future.

A other note, please try and commit to the Dev branches as the main branches are classed as stable and we normally test stuff internally before we push to main. 

I will merge in the next couple of days as I will be preparing a release for Blender 4.2. 

I won't be backporting any new features to older Cats versions as these versions are end of life anyway.

**Comment by RinaDev-xyz** [comment]
Merge with Stable and backported to Dev.

**Review by RinaDev-xyz — COMMENTED** [review]
Good

**Comment by ptrcortes** [comment]
Sorry for the delay in responding. Thank you for your patience and for explaining that to me!

If I want to do more work in the future, should I only be working on the avatar toolkit you mentioned?

**Comment by RinaDev-xyz** [comment]
Hi there, sorry for the late reply. This is correct, we are not adding any major features to Cats now and Cats is in maintaince mode only as we are working on Avatar Toolkit which will completely replace cats. We are aiming for an Alpha release for Avatar Toolkit for Blender 5.0. 

More info here: https://neoneko.xyz/avatar-toolkit.html
Github here: https://github.com/teamneoneko/Avatar-Toolkit

**Pull request merged**
